### ISSUE TITLE
We need more about #DataSchema related conceptual bases to support

### ISSUE THREAD

**Issue by sspaeti** [airbytehq/glossary#2]
Based on Nick Vintila [here](https://twitter.com/semanticbeeng/status/1569603622778056705): We need more about [#DataSchema](https://twitter.com/hashtag/DataSchema?src=hashtag_click) related conceptual bases to support [#TypeLevel](https://twitter.com/hashtag/TypeLevel?src=hashtag_click) [#DataLineage](https://twitter.com/hashtag/DataLineage?src=hashtag_click) https://twitter.com/semanticbeeng/status/1491105417111683076

Unless we unify API and DAPI we cannot have [#DataGovernance](https://twitter.com/hashtag/DataGovernance?src=hashtag_click) in ... code.

**Comment by sw-yx** [comment]
sorry accidental click... 

type level data lingeage seems a bit advanced. what's our coverage for fundamental concepts before we go to niche stuff?

**Comment by sspaeti** [comment]
Yeah, I agree, I wouldn't go that deep. I would check how it connects to our current terms, such as data lineage, schema evolution, and data governance. E.g., column lineage was something I was always interested in digging into more, so that could be the first start. 

Types are more advanced, but something very popular with modern programming languages such as rust and frameworks such as dagster or delta lake enforce these types. I added a label `advanced` so we can do these later. Probably it's a good one to do later when time.

**Comment by sw-yx** [comment]
sounds good!
